version: "3"
services:
  logstash:
    image: elastic/logstash:7.7.1
    restart: always
    container_name: logstash
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /root/common/data/logstash/pipeline:/usr/share/logstash/pipeline
      - /root/common/data/logstash/log:/var/log/glog/
      - /root/common/data/logstash/lib/mysql-connector-java-8.0.18.jar:/usr/share/logstash/logstash-core/lib/jars/mysql-connector-java-8.0.18.jar
      - /root/common/data/logstash/lib/mysql-connector-java-8.0.18.jar:/resource/mysql-connector-java-8.0.18.jar
      - /root/common/data/logstash/order/:/usr/share/logstash/last_values/
